# Generated by Django 5.1.7 on 2025-03-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='servicebooking',
            options={'ordering': ['-booking_date'], 'verbose_name_plural': 'Service Bookings'},
        ),
        migrations.AlterModelOptions(
            name='servicecompletion',
            options={'ordering': ['-completion_date'], 'verbose_name_plural': 'Service Completions'},
        ),
    ]
